### PR TITLE
Imrpove severe logging with exception in seperate parameter

### PR DESCRIPTION
**Pull request by zhang123cnn**
Summary:
Move the exception severe logging to the seperate parameter. So it can
be better displayed and parsed by logging framework.

Test Plan: Built/tested/loglined

Reviewers: #dtp

Subscribers:

Tasks: T81987523

Tags:

Blame Revision:

Differential Revision: https://phabricator.intern.facebook.com/D25824059

### CODE REVIEW

**Comment by zhang123cnn** [comment]
@seehamrun Hey Siham, do you mind taking a look at this PR? It should be a simple change to improve the logging. Let me know if you have any concerns.

**Review by seehamrun — APPROVED** [review]
Not related, but I think we've brought up issues before with the inconsistent monitoring formats since the Monitor takes a String List as an argument which leads to some confusion depending on the implementation. Details in #702

**Comment by seehamrun** [comment]
Also not sure if you saw, but it looks like this opens up 1 issue: 
```
This pull request introduces 1 alert when merging 46d78ce into d5c4479 - view on LGTM.com

new alerts:

1 for Unused format argument
```

**Comment by zhang123cnn** [comment]
@seehamrun Yes, I am aware of that issue. It was triggered for the first revision of this PR. I have fixed it now so if you check latest LGTM page, it is all good now

**Pull request merged**
