### PR TITLE
User serviceLoader for loading the CloudExtension in worker-main

### PR DESCRIPTION
**Pull request by seehamrun**
#208

### CODE REVIEW

**Comment by rtannenbaum** [comment]
woot! does it run locally?

**Comment by seehamrun** [comment]
I'm having some issues running locally using the build script since I couldnt get the docker env working. 

But running locally through gradle manually, I verified that the right ExtensionContext was picked in the logger after removing the explicit dependencies on GoogleCloud

**Comment by rtannenbaum** [comment]
If you want to test it w/ Google Cloud you'll need to use the docker script since it sets GCP-specific environment vars within the container. You'll need to download service account creds for the project too if you don't have them.

./config/gcp/build_and_upload_docker_image.sh worker local qa

I have the files set up so can try it in the office, feel free to merge it in the meantime

**Comment by seehamrun** [comment]
Yea I ran into issues because I had made some changes to the old build script and forgot that there was the docker image script as well (sorry!) - I'm going to submit for now until we determine how to fix the build script (dont want to step on your toes).

**Pull request merged**
