### PR TITLE
Updating developer documentation for Facebook

### PR DESCRIPTION
**Pull request by umarmustafa**
Added a README for Facebook extension, listing how to get keys and any other support. Also linked it from the Keys page in documentation.

### CODE REVIEW

**Review by wmorland — APPROVED** [review]
Looks good to me

**Comment by hoandesign** [comment]
@umarmustafa I just tested Notes export to Google Docs flow and there are some bugs:
- No line breaks, formating headers
- Some notes are not exported or blank.

**Comment by hoandesign** [comment]
The same problem happened with notes to Blogger. The note only includes the link to the orginal post.

Also, the title should be the note name, not the timestamp log.

Screen Shot 2021-08-09 at 21 34 28

**Comment by seehamrun** [comment]
@hoandesign can you please file a separate issue for this so it can be tracked?

**Pull request merged**
