### PR TITLE
Remove jdk transport extension (may add it back later if refactored)

### PR DESCRIPTION
**Pull request by rtannenbaum**
Tested running a photos transfer with the demo server

### CODE REVIEW

**Comment by rtannenbaum** [comment]
More context: we are switching to the new restful model implemented by the jettyrest transport extension, where OAuth callbacks are separate from the API server. (In our demo server, they are handled by our Angular client after being forwarded back from nginx). In other implementations, they may be handled by other frontends.

Since the old jdk transport extension implemented OAuth handlers there and is inconsistent, we're removing it to avoid confusion, but may add it back if we refactor it to follow the new model. The more transport options we provide, the better, there is nothing inherently wrong with using 'jdk' (i.e. sun's HTTP server)

**Comment by rtannenbaum** [comment]
@holachuy I updated the comment to reflect our offline discussion

**Comment by holachuy** [comment]
Thanks! Can we check that all tests pass before submitting, in case anything depended on this?

**Comment by rtannenbaum** [comment]
Java tests and demo image build are passing via Travis (I also tested a local run with the demo image) but the Angular tests actually need to be updated for the new rest client, so nothing to test there yet (https://github.com/google/data-transfer-project/issues/511)

**Pull request merged**
