### PR TITLE
Want to improve documentation

### PR DESCRIPTION
**Pull request by gauravsavanur07**
cross chain implementation with etherium channels

### CODE REVIEW

**Comment by rtannenbaum** [comment]
Hey Gaurav, something looks off with this PR, could you try rebasing off of master perhaps? Right now it's showing a very long commit history for me that look to be all from master (i.e. no new commits).

**Comment by gauravsavanur07** [comment]
Ill try to rebase my commits

**Comment by seehamrun** [comment]
Hey Gaurav, Could you try and rebase again? The commit history looks to be all updates from master to the branch. Otherwise we can close this PR and you can try and submit another clean one from master. 

Thanks!

**Comment by seehamrun** [comment]
Hi Gaurav, since this hasn't been updated in a while, I'm going to close out this PR. Feel free to reopen or submit a new one once its been cleaned up! 

Thanks!

**Pull request closed without merging**
